### ISSUE TITLE
[Feat] 학생회 공지사항

### ISSUE THREAD

**Issue by jeoungsung12** [Creative-Semester/server#63]
<학생회 공지사항>
Q. 학생회 공지사항에는 댓글이 없나요?
Q. 학생회 공지사항에는 게시글 상세 조회 기능이 없나요? -> ismine을 못 받아 게시글 삭제 안됨.

이상입니다. 아직 개발을 안해서 그런거라면 천천히 해주셔도 되고, 그냥 안돼서 궁금 ㅎㅎ 
시간 날때 봐주세용

**Comment by jeoungsung12** [comment]
학생회 공지사항도 자유게시판이랑 동일한 문제 발생! 게시판에 글을 쓰면 가장 최근 글이 위로!!

**Comment by jaepyo-Lee** [comment]
A1. 정렬 문제는 오늘안에 해결하도록 하겠습니다!
A2. 학생회 공지와 자유게시글은 같은 api사용합니다! 쿼리파라미터로 구분하여 사용하시면 됩니다!

**Comment by jaepyo-Lee** [comment]
테스트 해봤는데, 잘 되는거같아서 해결되었나요~?

**Comment by jeoungsung12** [comment]
1. 게시판에 대한 정렬문제는 해결되었습니다.
2. 학생회 공지사항도 잘 돌아갑니다.(상세내용 조회 성공)
3. 댓글도 잘 입력되고 받아오지만, 댓글 정렬이 이상해졌습니다. 댓글 정렬은 최근 댓글이 아래로 가야합니다!
(게시판은 최신 글이 위로! 그대로 놔두면 될거 같습니다.)
4. 게시글에 대한 삭제는 Internal Server Error 가 아직 발생합니다.
5. 투표 전송에 대해서는 아직 "error": Bad Request 가 발생합니다. (ex)boardId = 44, VoteType = "AGREE"
6. 투표 조회는 잘 작동 됩니다.
