### ISSUE TITLE
[Feat] 투표 기능!

### ISSUE THREAD

**Issue by jeoungsung12** [Creative-Semester/server#64]
<투표>
Q. 투표는 댓글이 없나요?
Q. 투표에는 게시글 상세 조회 기능이 없나요? -> ismine을 못 받아 게시글 삭제 안됨.
투표도 자유게시판이랑 동일한 문제 발생! 게시판에 글을 쓰면 가장 최근 글이 위로!!

+ 투표 글 작성 통신 중에
바디 값입니다. - ["image": [["imageName": "", "imageUrl": ""]], "content": "투푷합시다!", "title": "사물함 투표", "deadLine": "2023-10-13"]
Response JSON: ["timestamp": 2023-10-06T18:34:57.114+00:00, "error": Bad Request, "status": 400, "path": /api/v1/boards]
이렇게 떴는데 제가 deadLine을 "yyyy-mm-dd"형식으로 포맷 해서 보내는데 혹시 "2023-10-06T17:52:46.468Z" 이런 형식으로 보내야하나요?ㅎㅎ

**Comment by jaepyo-Lee** [comment]
deadLine은 "yyyy-mm-dd hh:mm"형식으로 보내주셔야합니다!! 스웨거에 예제 추가한거로 기억하는데, 적용이 안되었나보네요!!

**Comment by jaepyo-Lee** [comment]
교수게시판을 제외한 모든  게시글은 같은 게시글 작성 api를 따르고 있습니다!

Q1. 투표가 추가되어있는 게시글도 댓글 작성 가능하게 만들었습니다! 투표없는 게시글과 동일하게 사용하시면 됩니다!
Q2. 게시글 상세조회시 투표가 존재안한다면 null이 들어가게됩니다. 상세조회 응답값에 isMine 포함되어있습니다!

**Comment by jaepyo-Lee** [comment]
@jeoungsung12 
혹시 해결되었나요?

**Comment by jeoungsung12** [comment]
@jaepyo-Lee 
1. 투표게시글에도 댓글 기능 해결되었습니다.
2. 투표 게시글도 Ismine 처리 잘 됩니다.
3. 감사합니다
