### ISSUE TITLE
[question] 학생회 공지사항 페이지, 투표 게시판 페이지 분리

### ISSUE THREAD

**Issue by jeoungsung12** [Creative-Semester/server#66]
형 혹시 나는 이렇게 공지사항이랑 투표글을 분리 해놨는데 같은 api로 불러오더라고 따로 글 가져오게 하는건 오래 걸리려나..?

학생회 공지사항 페이지로 들어가서 투표 게시판을 분리해서 놔뒀거든

<img width="361" alt="스크린샷 2023-10-07 오후 2 11 10" src="https://github.com/Creative-Semester/server/assets/50621327/d8e9d901-3488-4de5-a430-1dc4bb760da8">

**Comment by jaepyo-Lee** [comment]
자유게시판도 사진처럼 나눠있나요? 
자유게시판도 나눠있으면 오래걸리진 않을거같은데, 나눠져있지 않으면 조금 시간 걸릴거같아요!
