### ISSUE TITLE
[bug] 투표하는 기능

### ISSUE THREAD

**Issue by jeoungsung12** [Creative-Semester/server#67]
투표하는 기능을 연결해보려고 하는데, let apiUrl = URL(string: "http://15.164.161.53:8082/api/v1/boards/\(post.boardId)/vote?VoteType=\(VoteType)") 이렇게 똑바로 보내긴했어.
Bad Request가 나오더라구 내 문제인거는 아는데, 스웨거에서도 돌려보니까 Bad Request가 나와서 혹시나 나중에 확인 한번만 부탁드려도 될까용

**Comment by jaepyo-Lee** [comment]
그 pathVariable에 넣은값도 보내줄수 있나요?

**Comment by jaepyo-Lee** [comment]
@jeoungsung12 
uri값 수정해서 VoteType이 아닌 voteType으로 넣어줘야할거에요!
