### ISSUE TITLE
[Request] 부서별 공약의 이행률을 조회하는 api

### ISSUE THREAD

**Issue by alstn38** [Creative-Semester/server#76]
# 요청사항 내용
결과 값에서 주는 값이 적절치 않은 것 같습니다.
## 어떤 요청사항인가요?
promisePercentage": {
      "기획": 0.25,
      "문화": 0.5,
      "복지": 0.33
    }

키 밸류값으로 주시면 저는 어떤 키 값이 있는지 알지 못해 사용하기 어렵습니다.
예) 체육학과는 기획이 아닌 체육일수도 있음.

"promisePercentage": [
    {
      "percent": 0.35,
      "name": "복지"
    },
    {
      "percent": 0.2,
      "name": "문화"
    },
    {
      "percent": 0.3,
      "name": "기획"
    }
  ]
  과 같은 리스트 형식으로 주시면 좋을 것 같습니다.

**Comment by jaepyo-Lee** [comment]
확인했습니다~ 수정한 후 코멘트 하도록 하겠습니다~

**Comment by jaepyo-Lee** [comment]
@alstn38 수정했습니다. 확인부탁드립니다~

**Comment by alstn38** [comment]
@jaepyo-Lee 확인했습니다. 잘 적용되었습니다. 감사합니다!
