### ISSUE TITLE
[error] 게시판 조회 api

### ISSUE THREAD

**Issue by jaepyo-Lee** [Creative-Semester/server#8]
### 이슈
![image](https://github.com/Creative-Semester/server/assets/74135929/f56ccd6c-12a7-4689-95ea-91924e9c7487)
![image](https://github.com/Creative-Semester/server/assets/74135929/ed77c11f-ef5a-400e-aa8d-f69b117e14fc)

PathVariable에 같은값이 들어오면 해당 api 두개중 어느 api를 호출한지 몰라 Ambiguous handler methods 에러가 뜹니다. url 수정 필요할것 같습니다.

**Comment by wjd4204** [comment]
해당 pr 완료되고 하겠습니다.
그리고 controller질문인데 상세조회의 Mapping이 /boards/{majorId}/{boardId}가 되어야 하나요? 아니면 /boards/{boardId}가 되어야 하나요?

**Comment by wjd4204** [comment]
수정하였습니다:)
